# Generated by Django 3.1.3 on 2020-11-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_auto_20201123_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pages_count',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
