# Generated by Django 3.1.3 on 2021-01-03 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0007_reader'),
    ]

    operations = [
        migrations.CreateModel(
            name='Librarian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookcopy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.bookcopy')),
                ('given_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.librarian')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.reader')),
            ],
        ),
    ]
