# Generated by Django 3.1.3 on 2021-01-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0008_librarian_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='librarian',
            options={'verbose_name_plural': 'Librarians'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Orders'},
        ),
        migrations.AddField(
            model_name='librarian',
            name='employeed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='librarian',
            name='unemployeed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='taken_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
